apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: weblayers
data:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: weblayers
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_URL: postgresql://postgres:postgres@postgres:5432/weblayers