name: CI/CD

env:
  # ← Load your Docker Hub username from Secrets
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  # ← Build your repo path directly off that same Secret
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/weblayers

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # (optional) run Linters / Tests here
      - name: Install Dependencies & Run Tests
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          # pytest or similar if you have tests

      - name: Build Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: weblayers-backend:latest

      - name: Build Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: weblayers-frontend:latest

  publish:
    name: Publish & Deploy
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}-backend:${{ github.ref_name }}
            ${{ env.DOCKERHUB_REPO }}-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}-frontend:${{ github.ref_name }}
            ${{ env.DOCKERHUB_REPO }}-frontend:latest

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: v0.20.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy Namespace
        run: |
          kubectl apply -f k8s/namespaces.yaml

      - name: Create DockerHub Pull Secret
        env:
          DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          kubectl create secret docker-registry dockerhub-reg \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=$DH_USER \
            --docker-password=$DH_TOKEN \
            --namespace=weblayers \
            --dry-run=client -o yaml \
          | kubectl apply -f -

      - name: Deploy to Kind
        run: |
          kubectl apply -f k8s/namespaces.yaml
          kubectl apply -n weblayers -f k8s/configmap.yaml
          kubectl apply -n weblayers -f k8s/postgres-deployment.yaml
          kubectl apply -n weblayers -f k8s/backend-deployment.yaml
          kubectl apply -n weblayers -f k8s/frontend-deployment.yaml